import { defineStore } from 'pinia';
import { ref, computed, reactive } from 'vue';
import { profileService } from '../services/profile.service';

export const useProfileStore = defineStore('profile', () => {
    // State
    const profiles = ref([]);
    const runningIds = ref([]);
    const launchingIds = ref([]);
    // Per-launch window frame color (hex), keyed by profile.id. Set when a
    // profile launches with watermark off; drives the card border. Runtime
    // only (not persisted) — matches the browser's --install-autogenerated-theme.
    const frameColors = reactive({});
    // Per-profile launch progress. Keyed by profile.id.
    // Present entry ⇒ ProfileCard renders inline progress bar. Cleared when
    // launch completes or fails so parallel launches don't clobber each other.
    const launchProgress = reactive({});
    // Per-profile launch/runtime error. Keyed by profile.id.
    // Present entry ⇒ ProfileCard renders inline error banner.
    // Cleared on: (a) next launch attempt from this profile, (b) user click
    // to dismiss, (c) app restart (memory-only, not persisted).
    const launchError = reactive({});
    const searchText = ref('');
    const selectedTag = ref('');
    const selectedIds = ref([]);
    const viewMode = ref(localStorage.getItem('geekez_view') || 'list');

    // Pagination state
    const currentPage = ref(1);
    const pageSize = ref(15);
    const totalCount = ref(0);
    const totalPages = ref(0);
    const availableTags = ref([]);
    const sortOrder = ref(localStorage.getItem('geekez_sort') || 'DESC');

    // Actions
    const loadProfiles = async () => {
        try {
            const result = await profileService.loadProfilesPaged({
                page: currentPage.value,
                pageSize: pageSize.value,
                search: searchText.value,
                tag: selectedTag.value,
                sortOrder: sortOrder.value
            });
            profiles.value = result.items;
            totalCount.value = result.totalCount;
            totalPages.value = result.totalPages;

            const runtimeState = await profileService.getRuntimeState();
            runningIds.value = runtimeState?.runningIds || await profileService.getRunningIds();
            launchingIds.value = runtimeState?.launchingIds || [];
            // Restore per-launch frame colors so card borders survive a refresh.
            const rc = runtimeState?.frameColors || {};
            Object.keys(frameColors).forEach(k => { if (!(k in rc)) delete frameColors[k]; });
            Object.assign(frameColors, rc);
            const profileIdSet = new Set(profiles.value.map(p => p.id));
            selectedIds.value = selectedIds.value.filter(id => profileIdSet.has(id));
        } catch (e) {
            console.error('Failed to load profiles:', e);
        }
    };

    const loadTags = async () => {
        try {
            availableTags.value = await profileService.getAllTags();
        } catch (e) {
            console.error('Failed to load tags:', e);
        }
    };

    const toggleViewMode = () => {
        viewMode.value = viewMode.value === 'list' ? 'grid' : 'list';
        localStorage.setItem('geekez_view', viewMode.value);
    };

    const setSearchText = (text) => {
        searchText.value = text;
        currentPage.value = 1;
        loadProfiles();
    };

    const setSelectedTag = (tag) => {
        selectedTag.value = tag || '';
        currentPage.value = 1;
        loadProfiles();
    };

    const setPage = (page) => {
        currentPage.value = page;
        loadProfiles();
    };

    const toggleSortOrder = () => {
        sortOrder.value = sortOrder.value === 'ASC' ? 'DESC' : 'ASC';
        localStorage.setItem('geekez_sort', sortOrder.value);
        currentPage.value = 1;
        loadProfiles();
    };

    // Getters
    const filteredProfiles = computed(() => profiles.value);

    const selectedCount = computed(() => selectedIds.value.length);

    const isSelected = (id) => selectedIds.value.includes(id);

    const toggleSelected = (id, forceValue = null) => {
        const has = selectedIds.value.includes(id);
        const shouldSelect = forceValue === null ? !has : !!forceValue;
        if (shouldSelect && !has) selectedIds.value.push(id);
        if (!shouldSelect && has) selectedIds.value = selectedIds.value.filter(item => item !== id);
    };

    const clearSelection = () => {
        selectedIds.value = [];
    };

    const toggleSelectAllFiltered = () => {
        const filteredIds = filteredProfiles.value.map(profile => profile.id);
        const allSelected = filteredIds.length > 0 && filteredIds.every(id => selectedIds.value.includes(id));
        if (allSelected) {
            selectedIds.value = selectedIds.value.filter(id => !filteredIds.includes(id));
            return;
        }
        const next = new Set(selectedIds.value);
        filteredIds.forEach(id => next.add(id));
        selectedIds.value = Array.from(next);
    };

    const isRunning = (id) => runningIds.value.includes(id);
    const isLaunching = (id) => launchingIds.value.includes(id);
    const getFrameColor = (id) => frameColors[id] || null;
    const getLaunchProgress = (id) => launchProgress[id] || null;

    const setLaunchProgress = (id, payload) => {
        if (!id) return;
        launchProgress[id] = payload;
    };

    const clearLaunchProgress = (id) => {
        if (!id) return;
        delete launchProgress[id];
    };

    const getLaunchError = (id) => launchError[id] || null;

    const setLaunchError = (id, payload) => {
        if (!id || !payload) return;
        launchError[id] = {
            message: payload.message || '',
            stderrTail: payload.stderrTail || '',
            kind: payload.kind || 'launch-failed',
            at: Date.now()
        };
    };

    const clearLaunchError = (id) => {
        if (!id) return;
        delete launchError[id];
    };

    const createProfile = async (data) => {
        try {
            await profileService.saveProfile(data);
            await loadProfiles();
            await loadTags();
        } catch (e) {
            console.error('Failed to create profile:', e);
            throw e;
        }
    };

    const updateProfile = async (profile) => {
        try {
            await profileService.updateProfile(profile);
            await loadProfiles();
            await loadTags();
        } catch (e) {
            console.error('Failed to update profile:', e);
            throw e;
        }
    };

    const deleteProfile = async (id) => {
        try {
            await profileService.deleteProfile(id);
            if (profiles.value.length === 1 && currentPage.value > 1) {
                currentPage.value--;
            }
            await loadProfiles();
            await loadTags();
        } catch (e) {
            console.error('Failed to delete profile:', e);
            throw e;
        }
    };

    return {
        profiles,
        runningIds,
        launchingIds,
        frameColors,
        getFrameColor,
        launchProgress,
        getLaunchProgress,
        setLaunchProgress,
        clearLaunchProgress,
        launchError,
        getLaunchError,
        setLaunchError,
        clearLaunchError,
        searchText,
        selectedTag,
        selectedIds,
        viewMode,
        // Pagination
        currentPage,
        totalCount,
        totalPages,
        availableTags,
        sortOrder,
        // Actions
        loadProfiles,
        loadTags,
        toggleViewMode,
        setSearchText,
        setSelectedTag,
        setPage,
        toggleSortOrder,
        // Getters
        filteredProfiles,
        selectedCount,
        isSelected,
        toggleSelected,
        clearSelection,
        toggleSelectAllFiltered,
        isRunning,
        isLaunching,
        createProfile,
        updateProfile,
        deleteProfile
    };
});
